#!/usr/bin/env python3
"""
Generate the ubi.world ledger explorer pages from signed JSON receipts.

Reads every `{LEDGER_ROOT}/transactions/*.json` and writes three page
types one level up:

    {LEDGER_ROOT}/../index.html                   home dashboard
    {LEDGER_ROOT}/../tx/<id>.html                 one per transaction
    {LEDGER_ROOT}/../handle/<handle>.html         one per handle (urlencoded)
    {LEDGER_ROOT}/../style.css                    design tokens (Tiramisu v2)

Idempotent — running twice in a row produces identical bytes. Runs in
under a second for the MVP-scale 9–100 transactions. Designed to be
cron-driven at one-minute cadence (`* * * * *`).

Usage:
    python3 generate_ledger_site.py
    python3 generate_ledger_site.py --ledger-root /home/vrgli/ubi.world/ledger

If --ledger-root isn't passed, falls back to $LEDGER_ROOT then to the
config module's default. Exits 0 even if there are zero transactions —
the home dashboard renders with "No transactions yet".
"""

from __future__ import annotations

import argparse
import html
import json
import logging
import os
import sys
import urllib.parse
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Iterable

# Make sure we can import config when run from anywhere.
_HERE = Path(__file__).resolve().parent
_BOT_ROOT = _HERE.parent
if str(_BOT_ROOT) not in sys.path:
    sys.path.insert(0, str(_BOT_ROOT))

try:
    import config  # noqa: E402
except Exception:
    config = None  # type: ignore

logger = logging.getLogger("ubi.gen")

# --------------------------------------------------------------------------- #
# Constants / formatting helpers
# --------------------------------------------------------------------------- #

GENERATED_NOTE = "Generated by tools/generate_ledger_site.py — do not edit by hand."


def fmt_hms(seconds: int) -> str:
    """Render seconds as `HHh MMm SSs` (book spec)."""
    s = int(seconds)
    h, rem = divmod(s, 3600)
    m, sec = divmod(rem, 60)
    return f"{h}h {m:02d}m {sec:02d}s"


def fmt_short(seconds: int) -> str:
    """Compact form for table cells: `1h 23m 04s` or `42m 18s`."""
    s = int(seconds)
    h, rem = divmod(s, 3600)
    m, sec = divmod(rem, 60)
    if h:
        return f"{h}h {m:02d}m {sec:02d}s"
    if m:
        return f"{m}m {sec:02d}s"
    return f"{sec}s"


def fmt_iso_human(iso: str) -> str:
    """`2026-05-22T17:34:25Z` -> `2026-05-22 17:34 UTC`."""
    try:
        dt = datetime.strptime(iso, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except ValueError:
        return iso
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def handle_url(handle: str) -> str:
    """URL-encode a handle for use in /handle/<x>.html links.

    The file on disk has a raw `:` in its name (see `handle_filename`);
    we URL-encode in links so the resulting URL is RFC-clean. Apache
    decodes the `%3A` back to `:` before file lookup, so both encoded
    and raw forms resolve to the same file.
    """
    return urllib.parse.quote(handle, safe="")


def handle_filename(handle: str) -> str:
    """On-disk filename for a handle's detail page.

    Uses the raw handle (with `:`) so Apache's URL-decoding step
    matches the filename. Writing the file with literal `%3A` in the
    name results in 404s because Apache decodes the URL before the
    filesystem lookup.
    """
    # Strip any characters that would actually break a filesystem.
    # Handles legally contain `:` and ASCII alnum; everything else
    # we conservatively percent-encode to be safe.
    safe = []
    for ch in handle:
        if ch.isalnum() or ch in (":", "-", "_", "."):
            safe.append(ch)
        else:
            safe.append("_")
    return "".join(safe) + ".html"


# --------------------------------------------------------------------------- #
# Load + index
# --------------------------------------------------------------------------- #

def load_transactions(tx_dir: Path) -> list[dict]:
    txs = []
    if not tx_dir.exists():
        return txs
    for path in sorted(tx_dir.glob("tx_*.json")):
        try:
            txs.append(json.loads(path.read_text()))
        except Exception as exc:
            logger.warning("skipping malformed %s: %s", path, exc)
    return txs


def index_by_handle(txs: list[dict]) -> dict[str, list[dict]]:
    """Group transactions by handle (both sent and received)."""
    by_handle: dict[str, list[dict]] = defaultdict(list)
    for tx in txs:
        by_handle[tx["from_handle"]].append(tx)
        if tx["to_handle"] != tx["from_handle"]:
            by_handle[tx["to_handle"]].append(tx)
    # Sort each handle's transactions newest-first.
    for h in by_handle:
        by_handle[h].sort(key=lambda t: t.get("timestamp_iso", ""), reverse=True)
    return by_handle


# --------------------------------------------------------------------------- #
# Templates (Tiramisu v2 design system — warm cream / dark charcoal)
# --------------------------------------------------------------------------- #

# Inlined CSS. Borrowed directly from the existing /home/vrgli/ubi.world/
# index.html (Tiramisu's deployed v2). Kept here so the ledger pages
# render identically whether served as static files or previewed locally.
STYLE_CSS = r"""
/* ubi.world ledger — book-family design system
   Warm cream light / deep dark, Georgia serif body, system sans chrome */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root{
  --bg:#16161a;
  --bg-elev:#1d1d23;
  --fg:#e8e6df;
  --muted:#a8a69e;
  --rule:#2c2c33;
  --rule-strong:#3a3a42;
  --accent:#d6c7a8;
  --link:#d6c7a8;
  --link-hover:#ffffff;
  --code-bg:#22222a;
  --side-bg:#101014;
  --side-active-bg:#22222a;
  --side-active-fg:#ffffff;
  --side-active-bar:#d6c7a8;
  --row-hover:#1a1a20;
}
[data-theme="light"]{
  --bg:#f6f1e3;
  --bg-elev:#efe8d3;
  --fg:#1d1d1b;
  --muted:#5a5a55;
  --rule:#d8d0bb;
  --rule-strong:#bdb39a;
  --accent:#5a4632;
  --link:#5a4632;
  --link-hover:#1d1d1b;
  --code-bg:#ece5cf;
  --side-bg:#efe8d3;
  --side-active-bg:#e6dcc0;
  --side-active-fg:#1d1d1b;
  --side-active-bar:#5a4632;
  --row-hover:#ece4ca;
}

html{scroll-behavior:smooth}
body{
  background:var(--bg);
  color:var(--fg);
  font-family: Georgia, "Iowan Old Style", "Apple Garamond", "Palatino Linotype", "Times New Roman", serif;
  line-height:1.7;
  font-size:18px;
  -webkit-text-size-adjust:100%;
  min-height:100vh;
}

.site-chrome{
  position:sticky;top:0;z-index:50;background:var(--bg);
  border-bottom:1px solid var(--rule);
  display:flex;align-items:center;justify-content:space-between;
  padding:0.55rem 1rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
}
.chrome-left{display:flex;align-items:center;gap:0.5rem}
.chrome-brand{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;
}
.theme-toggle{
  background:transparent;border:1px solid var(--rule-strong);color:var(--fg);
  font:inherit;font-size:1.05rem;width:2.1rem;height:2.1rem;padding:0;
  border-radius:50%;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;
}
.theme-toggle:hover{border-color:var(--accent);color:var(--accent)}
.menu-toggle{
  display:none;background:transparent;border:1px solid var(--rule-strong);
  color:var(--fg);font:inherit;font-size:0.85rem;padding:0.3rem 0.6rem;
  border-radius:4px;cursor:pointer;line-height:1;
}

.layout{
  display:grid;grid-template-columns:240px minmax(0,1fr);
  max-width:1180px;margin:0 auto;align-items:start;
}
.sidebar{
  position:sticky;top:3.2rem;align-self:start;
  max-height:calc(100vh - 3.2rem);overflow-y:auto;
  padding:1.4rem 1rem 2.5rem 1.5rem;border-right:1px solid var(--rule);
  background:var(--side-bg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
  font-size:0.9rem;line-height:1.45;
}
.sidebar-header{
  display:flex;align-items:center;justify-content:space-between;
  margin:0 -0.5rem 1rem;padding:0 0.5rem 0.85rem;
  border-bottom:1px solid var(--rule);
}
.sidebar-flag{
  display:inline-flex;align-items:center;gap:0.5rem;
  text-decoration:none;color:var(--fg);line-height:0;
}
.sidebar-flag img{height:22px;width:auto;border-radius:2px;opacity:0.95}
.sidebar-flag .brand{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;letter-spacing:0.14em;text-transform:uppercase;
  font-weight:700;color:var(--muted);line-height:1;
}
.sidebar-flag:hover .brand{color:var(--fg)}
.side-part{
  font-size:0.7rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;margin:1.1rem 0 0.35rem;
}
.side-part:first-of-type{margin-top:0.2rem}
.sidebar ul{list-style:none;margin:0 0 0.4rem;padding:0}
.sidebar li{margin:0}
.nav-link{
  display:block;text-decoration:none;color:var(--link);
  padding:0.34rem 0.55rem;margin:0.05rem -0.55rem;
  border-left:3px solid transparent;border-radius:0 3px 3px 0;
}
.nav-link:hover{color:var(--link-hover);background:var(--bg-elev)}
.sidebar .small-note{
  margin-top:1rem;padding:0.7rem 0.8rem;background:var(--bg-elev);
  border-radius:4px;font-size:0.82rem;color:var(--muted);line-height:1.5;
}
.sidebar .small-note strong{display:block;color:var(--fg);font-size:0.8rem;margin-bottom:0.3rem;text-transform:uppercase;letter-spacing:0.1em}
.side-eco{margin-top:1.5rem;padding-top:0.9rem;border-top:1px solid var(--rule)}

.wrap{max-width:880px;padding:2.8rem 2.2rem 4rem;margin:0}

.tagline{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;margin:0 0 1.2rem;
}
h1{
  font-family: Georgia, serif;font-weight:700;font-size:2.1rem;color:var(--fg);
  line-height:1.2;margin:0 0 1.2rem;letter-spacing:-0.01em;
}
h2{
  font-family: Georgia, serif;font-weight:700;font-size:1.5rem;color:var(--fg);
  margin:2.6rem 0 0.9rem;line-height:1.3;padding-bottom:0.4rem;
  border-bottom:1px solid var(--rule);
}
p{margin:0 0 1.05rem;max-width:65ch}
a{color:var(--link);text-decoration:none;border-bottom:1px solid transparent}
a:hover{color:var(--link-hover);border-bottom-color:var(--link-hover)}
strong{font-weight:700;color:var(--fg)}

code, .mono{
  font-family: "SF Mono", Menlo, Consolas, "Liberation Mono", monospace;
  font-size:0.88em;color:var(--accent);background:var(--code-bg);
  padding:0.1em 0.35em;border-radius:3px;border:1px solid var(--rule);
}

/* Stats grid (home) */
.stats-grid{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));
  gap:0.9rem;margin:1.4rem 0 0.4rem;
}
.stat-card{
  background:var(--bg-elev);border:1px solid var(--rule);
  border-left:3px solid var(--accent);border-radius:0 4px 4px 0;
  padding:1rem 1.1rem;
}
.stat-card .label{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.74rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;margin-bottom:0.35rem;
}
.stat-card .value{
  font-family: Georgia, serif;font-size:1.55rem;font-weight:700;color:var(--fg);
  line-height:1.15;
}
.stat-card .sub{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;color:var(--muted);margin-top:0.25rem;
}

/* Transactions table */
.tx-table{
  width:100%;border-collapse:collapse;margin:1rem 0 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
  font-size:0.9rem;
}
.tx-table th, .tx-table td{
  text-align:left;padding:0.55rem 0.7rem;border-bottom:1px solid var(--rule);
  vertical-align:top;
}
.tx-table th{
  font-size:0.72rem;letter-spacing:0.14em;text-transform:uppercase;
  color:var(--muted);font-weight:700;border-bottom:1px solid var(--rule-strong);
}
.tx-table tr:hover td{background:var(--row-hover)}
.tx-table td.amount{font-family: "SF Mono", Menlo, Consolas, monospace;color:var(--fg);white-space:nowrap}
.tx-table td.time{font-family: "SF Mono", Menlo, Consolas, monospace;color:var(--muted);white-space:nowrap}
.tx-table td.handle{font-family: "SF Mono", Menlo, Consolas, monospace}
.blue-pill{
  display:inline-block;padding:0.05em 0.55em;border:1px solid var(--rule-strong);
  border-radius:999px;font-size:0.78em;color:var(--muted);background:var(--bg-elev);
}

/* Key/value list (tx detail) */
.kv{
  display:grid;grid-template-columns:max-content 1fr;column-gap:1.4rem;row-gap:0.55rem;
  margin:1rem 0 0;font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.92rem;
}
.kv dt{
  font-size:0.72rem;letter-spacing:0.12em;text-transform:uppercase;
  color:var(--muted);font-weight:700;padding-top:0.15rem;
}
.kv dd{margin:0;color:var(--fg);font-family: "SF Mono", Menlo, Consolas, monospace;word-break:break-all}
.kv dd.serif{font-family: Georgia, serif}

.sig-block{
  margin-top:0.4rem;padding:0.7rem 0.9rem;background:var(--code-bg);
  border:1px solid var(--rule);border-radius:4px;
  font-family: "SF Mono", Menlo, Consolas, monospace;font-size:0.8rem;
  color:var(--muted);word-break:break-all;
}
.sig-toggle{
  background:none;border:none;color:var(--link);cursor:pointer;
  font:inherit;font-size:0.78rem;padding:0;margin-left:0.4rem;
  border-bottom:1px solid var(--rule-strong);
}

footer{
  border-top:1px solid var(--rule);padding:1.1rem 0 0;margin-top:3rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  font-size:0.78rem;color:var(--muted);letter-spacing:0.05em;
}

@media (max-width:900px){
  .layout{grid-template-columns:1fr}
  .menu-toggle{display:inline-block}
  .sidebar{
    position:fixed;top:3.2rem;left:0;bottom:0;width:280px;z-index:40;
    transform:translateX(-100%);transition:transform 0.18s ease;
    border-right:1px solid var(--rule);box-shadow:2px 0 12px rgba(0,0,0,0.18);
  }
  .sidebar.open{transform:translateX(0)}
  body.sidebar-open{overflow:hidden}
  .sidebar-scrim{
    display:none;position:fixed;inset:3.2rem 0 0 0;
    background:rgba(0,0,0,0.45);z-index:35;
  }
  body.sidebar-open .sidebar-scrim{display:block}
}
@media (max-width:700px){
  body{font-size:17px}
  .wrap{padding:1.8rem 1.1rem 3rem}
  h1{font-size:1.7rem}
  h2{font-size:1.25rem}
  .site-chrome{padding:0.45rem 0.8rem}
  .tx-table{font-size:0.84rem}
  .tx-table th, .tx-table td{padding:0.45rem 0.45rem}
  .kv{grid-template-columns:1fr}
  .kv dt{padding-top:0.6rem}
}
"""

# Boot-time theme glue + chrome controls. Same as Tiramisu's deployed
# index.html so the toggle and mobile drawer behave identically.
THEME_SCRIPT = """<script>(function(){try{var t=localStorage.getItem('ubi-theme');document.documentElement.setAttribute('data-theme',t==='light'?'light':'dark');}catch(e){document.documentElement.setAttribute('data-theme','dark');}})();</script>"""

CHROME_SCRIPT = """<script>
(function(){
  var root=document.documentElement;
  function applyTheme(t){root.setAttribute('data-theme',t);var b=document.getElementById('themeBtn');if(b){var dark=t==='dark';b.setAttribute('aria-pressed',dark?'true':'false');b.setAttribute('title',dark?'Switch to light mode':'Switch to dark mode');b.innerHTML='<span class="glyph" aria-hidden="true">'+(dark?'\\u2600':'\\u263E')+'</span>';}}
  function currentTheme(){try{var v=localStorage.getItem('ubi-theme');return v==='light'?'light':'dark';}catch(e){return 'dark';}}
  applyTheme(currentTheme());
  var btn=document.getElementById('themeBtn');
  if(btn){btn.addEventListener('click',function(){var next=currentTheme()==='dark'?'light':'dark';try{localStorage.setItem('ubi-theme',next);}catch(e){}applyTheme(next);});}
  var sb=document.querySelector('.sidebar');
  var mbtn=document.getElementById('menuBtn');
  var scrim=document.querySelector('.sidebar-scrim');
  function closeSb(){if(sb)sb.classList.remove('open');document.body.classList.remove('sidebar-open');if(mbtn)mbtn.setAttribute('aria-expanded','false');}
  if(mbtn&&sb){mbtn.addEventListener('click',function(){var open=sb.classList.toggle('open');document.body.classList.toggle('sidebar-open',open);mbtn.setAttribute('aria-expanded',open?'true':'false');});}
  if(scrim){scrim.addEventListener('click',closeSb);}
  document.querySelectorAll('.sidebar a').forEach(function(a){a.addEventListener('click',function(){if(window.innerWidth<=900)closeSb();});});
  var sigToggle=document.getElementById('sigToggle');
  if(sigToggle){sigToggle.addEventListener('click',function(){var full=document.getElementById('sigFull');var trunc=document.getElementById('sigTrunc');var showing=full.style.display!=='none';full.style.display=showing?'none':'block';trunc.style.display=showing?'inline':'none';sigToggle.textContent=showing?'show full':'hide';});}
})();
</script>"""


def _sidebar_html(active: str = "home") -> str:
    """Build the shared sidebar. `active` controls which ecosystem link
    gets the highlighted state."""
    return f"""<nav class="sidebar" id="sidebar" aria-label="Site navigation">
  <div class="sidebar-header">
    <a class="sidebar-flag" href="/" aria-label="Time for UBI home">
      <img src="https://ubi.vision/UBI-Flag/UBI-Flag-120x100px.png" alt="UBI flag" width="29" height="22">
      <span class="brand">Time for UBI</span>
    </a>
  </div>

  <p class="side-part">What is this?</p>
  <div class="small-note">
    <strong>ubi.world</strong>
    The public mirror of every Time for UBI transaction. Each entry is
    signed by the node that recorded it. Anyone can audit.
  </div>

  <p class="side-part">Browse</p>
  <ul>
    <li><a href="/" class="nav-link">Latest transactions</a></li>
    <li><a href="/ledger/" class="nav-link">Raw signed JSONs &rarr;</a></li>
  </ul>

  <div class="side-eco">
    <p class="side-part">Ecosystem</p>
    <ul>
      <li><a href="https://ubi.vision" class="nav-link">Spec &rarr; ubi.vision</a></li>
      <li><a href="https://ubi.education" class="nav-link">Book &rarr; ubi.education</a></li>
      <li><a href="https://ubi.world" class="nav-link">Ledger &rarr; ubi.world</a></li>
    </ul>
  </div>
</nav>
<div class="sidebar-scrim" aria-hidden="true"></div>"""


def _page_shell(title: str, body: str, active: str = "home") -> str:
    """Wrap a page body in the shared chrome + sidebar."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<meta name="description" content="ubi.world — public ledger of Time for UBI transactions.">
<link rel="stylesheet" href="/style.css">
{THEME_SCRIPT}
</head>
<body>

<div class="site-chrome" role="banner">
  <div class="chrome-left">
    <button class="menu-toggle" id="menuBtn" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="sidebar">&#9776; Menu</button>
    <button class="theme-toggle" id="themeBtn" type="button" aria-label="Toggle dark or light mode" aria-pressed="true" title="Toggle dark / light"><span class="glyph" aria-hidden="true">&#9728;</span></button>
  </div>
  <span class="chrome-brand">Time for UBI &middot; Ledger</span>
</div>

<div class="layout">

{_sidebar_html(active)}

<main class="wrap">
{body}
<footer>ubi.world &middot; public ledger &middot; signed by participating nodes &middot; generated {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</footer>
</main>
</div>

{CHROME_SCRIPT}
</body>
</html>
"""


# --------------------------------------------------------------------------- #
# Page builders
# --------------------------------------------------------------------------- #

def _tx_row(tx: dict) -> str:
    tx_id = tx["id"]
    ts = fmt_iso_human(tx.get("timestamp_iso", ""))
    frm = tx["from_handle"]
    to = tx["to_handle"]
    amount = fmt_short(tx["amount_seconds"])
    blue = tx.get("blue_pct", 100)
    node = tx.get("from_node", "")
    return (
        f"<tr>"
        f"<td class=\"time\">{html.escape(ts)}</td>"
        f"<td class=\"handle\"><a href=\"/handle/{handle_url(frm)}.html\">{html.escape(frm)}</a></td>"
        f"<td class=\"handle\"><a href=\"/handle/{handle_url(to)}.html\">{html.escape(to)}</a></td>"
        f"<td class=\"amount\"><a href=\"/tx/{tx_id}.html\">{html.escape(amount)}</a></td>"
        f"<td><span class=\"blue-pill\">blue {blue}%</span></td>"
        f"<td class=\"handle\" style=\"color:var(--muted)\">{html.escape(node)}</td>"
        f"</tr>"
    )


def build_home(txs: list[dict], handles: Iterable[str]) -> str:
    """Home dashboard with stats block + latest 50 table."""
    total_tx = len(txs)
    total_handles = len(set(handles))

    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(hours=24)

    minted_24h = 0
    largest_24h = 0
    for tx in txs:
        try:
            ts = datetime.strptime(tx["timestamp_iso"], "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        except Exception:
            continue
        if ts >= cutoff:
            minted_24h += tx["amount_seconds"]
            if tx["amount_seconds"] > largest_24h:
                largest_24h = tx["amount_seconds"]

    # Build the table — newest first, cap at 50.
    txs_sorted = sorted(txs, key=lambda t: t.get("timestamp_iso", ""), reverse=True)
    latest = txs_sorted[:50]

    if latest:
        table_rows = "\n".join(_tx_row(t) for t in latest)
        table = f"""<table class="tx-table">
<thead>
<tr><th>Time (UTC)</th><th>From</th><th>To</th><th>Amount</th><th>Blue</th><th>Node</th></tr>
</thead>
<tbody>
{table_rows}
</tbody>
</table>"""
    else:
        table = "<p style=\"color:var(--muted)\">No transactions yet. The ledger fills as nodes come online.</p>"

    stats_html = f"""<div class="stats-grid">
  <div class="stat-card">
    <div class="label">Total transactions</div>
    <div class="value">{total_tx:,}</div>
    <div class="sub">since inception</div>
  </div>
  <div class="stat-card">
    <div class="label">Active handles</div>
    <div class="value">{total_handles:,}</div>
    <div class="sub">handles that have sent or received</div>
  </div>
  <div class="stat-card">
    <div class="label">Time moved (last 24h)</div>
    <div class="value">{fmt_short(minted_24h)}</div>
    <div class="sub">across all recorded transfers</div>
  </div>
  <div class="stat-card">
    <div class="label">Largest transfer (24h)</div>
    <div class="value">{fmt_short(largest_24h)}</div>
    <div class="sub">single signed receipt</div>
  </div>
</div>"""

    body = f"""<p class="tagline">Public ledger &middot; Time for UBI</p>
<h1>The time economy, transaction by transaction.</h1>
<p>
  Every transfer on the Time for UBI federation is signed by the node that recorded it,
  then mirrored here. The raw JSONs live at <a href="/ledger/">ubi.world/ledger</a>.
  This page renders them.
</p>

<h2>Network at a glance</h2>
{stats_html}

<h2>Latest transactions</h2>
{table}

<h2>How it works</h2>
<p>
  When a transaction completes on a participating node, that node signs the
  receipt with its Ed25519 private key and writes the signed JSON to its slice
  of <code>/ledger/transactions/</code>. A small generator re-renders this page
  every minute. Tampering would break the signature; anyone can verify offline
  using the signing node's public key.
</p>
<p>
  Read the full <a href="https://ubi.vision">specification at ubi.vision</a>, or
  the long-form rationale in the book at <a href="https://ubi.education">ubi.education</a>.
</p>
"""
    return _page_shell("ubi.world — public ledger of Time for UBI", body, active="home")


def build_tx_detail(tx: dict) -> str:
    tx_id = tx["id"]
    amount = fmt_hms(tx["amount_seconds"])
    blue = tx.get("blue_pct", 100)
    red = 100 - blue
    ts = fmt_iso_human(tx.get("timestamp_iso", ""))
    frm = tx["from_handle"]
    to = tx["to_handle"]
    sig = tx.get("node_signature", "")
    sig_trunc = (sig[:16] + "…" + sig[-16:]) if len(sig) > 40 else sig

    body = f"""<p class="tagline">Transaction &middot; {html.escape(tx_id)}</p>
<h1>{html.escape(amount)} &mdash; {html.escape(frm)} <span style="color:var(--muted)">&rarr;</span> {html.escape(to)}</h1>
<p style="color:var(--muted)">{html.escape(ts)} &middot; signed by <code>{html.escape(tx.get("signing_node_domain", ""))}</code></p>

<h2>Receipt</h2>
<dl class="kv">
  <dt>Transaction ID</dt>           <dd>{html.escape(tx_id)}</dd>
  <dt>Type</dt>                     <dd>{html.escape(tx.get("type", "transfer"))}</dd>
  <dt>From</dt>                     <dd><a href="/handle/{handle_url(frm)}.html">{html.escape(frm)}</a></dd>
  <dt>To</dt>                       <dd><a href="/handle/{handle_url(to)}.html">{html.escape(to)}</a></dd>
  <dt>From node</dt>                <dd>{html.escape(tx.get("from_node", ""))}</dd>
  <dt>To node</dt>                  <dd>{html.escape(tx.get("to_node", ""))}</dd>
  <dt>Amount</dt>                   <dd>{html.escape(amount)} <span style="color:var(--muted)">({tx["amount_seconds"]:,} seconds)</span></dd>
  <dt>Blue / Red</dt>               <dd>blue {blue}% &middot; red {red}%</dd>
  <dt>Timestamp (UTC)</dt>          <dd>{html.escape(ts)}</dd>
  <dt>Signed at</dt>                <dd>{html.escape(fmt_iso_human(tx.get("signed_at_iso", "")))}</dd>
  <dt>Signing node</dt>             <dd>{html.escape(tx.get("signing_node_domain", ""))}</dd>
  <dt>Node fingerprint</dt>         <dd>{html.escape(tx.get("signing_node_public_key_fingerprint", ""))}</dd>
  <dt>Ledger format</dt>            <dd>{html.escape(tx.get("ledger_format_version", ""))}</dd>
</dl>

<h2>Signature
  <span id="sigTrunc" style="font-family:'SF Mono',Menlo,monospace;font-size:0.78rem;color:var(--muted);font-weight:400">
    {html.escape(sig_trunc)}
    <button id="sigToggle" class="sig-toggle" type="button">show full</button>
  </span>
</h2>
<div id="sigFull" class="sig-block" style="display:none">{html.escape(sig)}</div>

<p style="margin-top:1.2rem">
  Raw signed JSON: <a href="/ledger/transactions/{html.escape(tx_id)}.json">/ledger/transactions/{html.escape(tx_id)}.json</a>
</p>
"""
    return _page_shell(f"{tx_id} — ubi.world", body, active="tx")


def build_handle_detail(handle: str, txs_for_handle: list[dict]) -> str:
    """Handle page — sent / received lists + simple totals."""
    sent = [t for t in txs_for_handle if t["from_handle"] == handle]
    received = [t for t in txs_for_handle if t["to_handle"] == handle and t["from_handle"] != handle]

    total_sent = sum(t["amount_seconds"] for t in sent)
    total_received = sum(t["amount_seconds"] for t in received)

    # Aggregate blue/red across all transfers (sent — that's where the
    # receiver assigned the rating; received doesn't carry this handle's
    # own rating).
    rated = sent  # sender's transactions carry the rating recipient gave
    if rated:
        avg_blue = sum(t.get("blue_pct", 100) for t in rated) / len(rated)
        blue_label = f"{avg_blue:.0f}% blue / {100 - avg_blue:.0f}% red"
    else:
        blue_label = "n/a"

    def tx_table(rows: list[dict], empty_msg: str) -> str:
        if not rows:
            return f"<p style=\"color:var(--muted)\">{empty_msg}</p>"
        body = "\n".join(_tx_row(t) for t in rows)
        return f"""<table class="tx-table">
<thead><tr><th>Time (UTC)</th><th>From</th><th>To</th><th>Amount</th><th>Blue</th><th>Node</th></tr></thead>
<tbody>{body}</tbody>
</table>"""

    stats = f"""<div class="stats-grid">
  <div class="stat-card">
    <div class="label">Total received</div>
    <div class="value">{fmt_short(total_received)}</div>
    <div class="sub">{len(received)} transfer{"s" if len(received)!=1 else ""}</div>
  </div>
  <div class="stat-card">
    <div class="label">Total sent</div>
    <div class="value">{fmt_short(total_sent)}</div>
    <div class="sub">{len(sent)} transfer{"s" if len(sent)!=1 else ""}</div>
  </div>
  <div class="stat-card">
    <div class="label">Blue / Red (outgoing)</div>
    <div class="value" style="font-size:1.1rem">{html.escape(blue_label)}</div>
    <div class="sub">how recipients rated this handle</div>
  </div>
</div>"""

    body = f"""<p class="tagline">Handle</p>
<h1><span style="font-family: 'SF Mono', Menlo, Consolas, monospace; color:var(--accent)">{html.escape(handle)}</span></h1>
<p>Public history of every transaction this handle is party to. Privacy is by design 100% public — every handle's full history is visible without opt-in.</p>

<h2>At a glance</h2>
{stats}

<h2>Received <span style="font-weight:400;font-size:1rem;color:var(--muted)">({len(received)})</span></h2>
{tx_table(received, "No incoming transfers yet.")}

<h2>Sent <span style="font-weight:400;font-size:1rem;color:var(--muted)">({len(sent)})</span></h2>
{tx_table(sent, "No outgoing transfers yet.")}
"""
    return _page_shell(f"{handle} — ubi.world", body, active="handle")


# --------------------------------------------------------------------------- #
# Atomic write helper
# --------------------------------------------------------------------------- #

def _atomic_write(path: Path, content: str) -> bool:
    """Write `content` to `path`, only touching the file if bytes differ.

    Returns True if the file was (re)written. This keeps the generator
    idempotent and avoids needlessly bumping mtimes (which would
    confuse Cloudflare's origin freshness checks).
    """
    new_bytes = content.encode("utf-8")
    if path.exists():
        try:
            if path.read_bytes() == new_bytes:
                return False
        except OSError:
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_bytes(new_bytes)
    os.replace(tmp, path)
    return True


# --------------------------------------------------------------------------- #
# Main entry point
# --------------------------------------------------------------------------- #

def generate(ledger_root: Path) -> dict:
    """Re-render all pages. `ledger_root` is the directory that contains
    `transactions/`; the output goes to its parent."""
    out_root = ledger_root.parent
    tx_dir = ledger_root / "transactions"

    txs = load_transactions(tx_dir)
    by_handle = index_by_handle(txs)
    all_handles = list(by_handle.keys())

    counts = {"home": 0, "tx": 0, "handle": 0, "style": 0, "txs_loaded": len(txs)}

    # style.css
    if _atomic_write(out_root / "style.css", STYLE_CSS.lstrip()):
        counts["style"] = 1

    # Home
    if _atomic_write(out_root / "index.html", build_home(txs, all_handles)):
        counts["home"] = 1

    # Transaction detail pages
    tx_out = out_root / "tx"
    for tx in txs:
        if _atomic_write(tx_out / f"{tx['id']}.html", build_tx_detail(tx)):
            counts["tx"] += 1

    # Handle detail pages — raw `:` on disk (Apache decodes %3A before
    # looking up the file, so encoded filenames 404). Links in the
    # generated HTML are URL-encoded so the *URLs* stay RFC-clean.
    handle_out = out_root / "handle"
    for handle, handle_txs in by_handle.items():
        if _atomic_write(handle_out / handle_filename(handle), build_handle_detail(handle, handle_txs)):
            counts["handle"] += 1

    return counts


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="ubi.world static-site generator")
    parser.add_argument("--ledger-root", default=None, help="root of the ledger (parent of transactions/)")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s  %(levelname)s  %(message)s",
    )

    root = args.ledger_root or os.environ.get("LEDGER_ROOT") or (getattr(config, "LEDGER_ROOT", None) if config else None)
    if not root:
        print("error: --ledger-root not given and LEDGER_ROOT not set", file=sys.stderr)
        return 2

    root_path = Path(root).expanduser()
    if not root_path.exists():
        print(f"error: ledger root does not exist: {root_path}", file=sys.stderr)
        return 2

    counts = generate(root_path)
    logger.info("generated: %s", counts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
